Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -2,48 +2,48 @@ name: Students file CI/CD
 
 on:
 
-push:
+ push:
 
-branches: [main]
+  branches: [main]
 
-pull_request:
+ pull_request:
 
-branches: [main]
+  branches: [main]
 
 jobs:
 
-check-students-file:
+ check-students-file:
 
-runs-on: ubuntu-latest
+  runs-on: ubuntu-latest
 
-steps:
+  steps:
 
-- name: Lejupieladet repozitorija kodu
+  - name: Lejupieladet repozitorija kodu
 
-  uses: actions/checkout@v4
+    uses: actions/checkout@v4
 
-- name: Parbaudit, vai eksiste Students.md
+  - name: Parbaudit, vai eksiste Students.md
 
-  run: |
+    run: |
 
-   if [ ! -f Students.md ]; then
+     if [ ! -f Students.md ]; then
 
-      echo "Kļūda: fails Students.md nav atrasts!"
+        echo "Kļūda: fails Students.md nav atrasts!"
 
-      exit 1
+        exit 1
 
-   fi
+     fi
 
-- name: Paradit Students.md saturu
+  - name: Paradit Students.md saturu
 
-  run: cat Students.md
+    run: cat Students.md
   
-- name: Testa solis
+  - name: Testa solis
 
-   run: echo "Parbaude veiksmigi izpildita"
+    run: echo "Parbaude veiksmigi izpildita"
 
-- name: Deploy (demo solis)
+  - name: Deploy (demo solis)
 
-if: success()
+    if: success()
 
-run: echo "Deploy veiksmīgs"
+    run: echo "Deploy veiksmīgs"
